import re
from typing import List, Tuple, Optional
import sqlite3
from db_data_exchanger import DBDataExchanger
import logging
import csv
import json


class DBDataCleaner:
    """Data cleaning utilities for the EasyNer database."""

    def __init__(
        self,
        conn: sqlite3.Connection,
        cursor: sqlite3.Cursor,
        logger: logging.Logger,
        data_exchanger: DBDataExchanger,
    ):
        self.conn = conn
        self.cursor = cursor
        self.logger = logger
        self.data_exchanger = data_exchanger

    def clean_entity_text_by_pattern(
        self, patterns: List[str], dry_run: bool = True
    ) -> List[Tuple]:
        """
        Clean entity occurrences by removing leading patterns and adjusting spans.

        Args:
            patterns: List of patterns to match at the start of entity_text
            dry_run: If True, only returns affected rows without making changes

        Returns:
            List of tuples (id, old_text, new_text, old_span, new_span) for affected rows
        """
        # Convert regex patterns to SQL LIKE patterns
        like_conditions = []
        params = []
        for pattern in patterns:
            # Escape special LIKE characters % and _
            escaped = pattern.replace("%", "\\%").replace("_", "\\_")
            like_conditions.append("entity_text LIKE ? ESCAPE '\\'")
            params.append(f"{escaped}%")

        # Find affected entries
        query = f"""
        SELECT id, entity_text, span_start, span_end 
        FROM entity_occurrences 
        WHERE {' OR '.join(like_conditions)}
        """

        affected_rows = []
        try:
            self.execute(query, params)
            rows = self.fetchall()

            for row in rows:
                id_, text, start, end = row
                # Still use regex for precise matching and capturing
                combined_pattern = f"^({'|'.join(patterns)})"
                match = re.match(combined_pattern, text)
                if match:
                    leading_len = len(match.group(0))
                    new_text = text[leading_len:].strip()
                    new_start = start + leading_len
                    affected_rows.append(
                        (id_, text, new_text, (start, end), (new_start, end))
                    )

            if not dry_run and affected_rows:
                # Update the database
                update_query = """
                UPDATE entity_occurrences 
                SET entity_text = ?,
                    span_start = ?
                WHERE id = ?
                """
                updates = [
                    (new_text, new_span[0], id_)
                    for id_, _, new_text, _, new_span in affected_rows
                ]

                self.bulk_insert(update_query, updates)
                self.commit()
                self.logger.info(f"Updated {len(updates)} entity occurrences")

        except Exception as e:
            self.logger.error(f"Error cleaning entity text: {e}")
            if not dry_run:
                self.rollback()
            raise

        return affected_rows

    def clean_inclusive_entity_spans(self, entity_type: str = None) -> None:
        """
        This fixes an error that seems to be produced when running the phrasematcher which produces inclusive span_end values in the entity_occurrences table, which is not the expected behavior.

        Python convention is to use exclusive end indices, which is what seem to be used for the entities generated by the NER model.

        This function will adjust the span_end values to be exclusive for all entity occurrences in the database of a given entity type.

        Args:
            entity_type: The type of entity to clean
            entity_id: The ID of

        """

        if entity_type is None:
            raise ValueError("entity_type must be specified")

        try:
            entities = self.data_exchanger.search_entities(type=entity_type)

            update_data = []
            for entity in entities:
                update_data.append((entity["span_end"] + 1, entity["id"]))

            if update_data:
                update_query = """
                UPDATE entity_occurrences
                SET span_end = ?
                WHERE id = ?
                """
                self.data_exchanger.bulk_insert(update_query, update_data)
                self.conn.commit()
                self.logger.info(
                    f"Updated span_end for {len(update_data)} entity occurrences of type {entity_type}"
                )
            else:
                self.logger.info(
                    f"No entity occurrences of type {entity_type} needed span adjustment."
                )

        except Exception as e:
            self.logger.error(f"Error cleaning inclusive entity spans: {e}")
            self.conn.rollback()
            raise

    def set_error_entity_error_codes(
        self,
        error_info: str = "/home/carloa/Desktop/EasyNer/dictionaries/misslabeled_ner.csv",
        error_codes_path: str = "entity_error_codes.json",
    ) -> None:
        """
        Attach error information to the entity_occurrences table. The error information is expected to be in the following format:

        entity_type,entity_text,error_id
        DIS,fires,MISSL
        DIS,forrest fire,MISSL
        DIS,earthquake,MISSL
        DIS,drought,MISSL

        Built in error codes are:
        {
            "error_codes": {
                "MISSP": "Misspelling",
                "MISSL": "Misslabeled Entity. Entity is not of the specified type",
                "AMBIG": "Ambiguous"
            }
        }

        This function will:
        0. read error_info.csv
        1. If not present create new TABLE entity_error_codes with columns id, error_id, error_description using entity_error_codes.sql
        2. Populate entity_error_codes with error_codes and corresponding error_description from error_info
        2. If not present: create a new column error_id in TABLE entity_occurrences that holds references to the entity_error_codes table entity_error_codes.id. Default value is NULL, which means no error
        3. Set entity_occurrences.error_id according to error_info["entity_errors"] for matching entity_type and entity_text

        Args:
            error_info: A dictionary containing error information as described above
        """

        error_codes = {
            "MISSP": "Misspelling",
            "MISSL": "Misslabeled Entity. Entity is not of the specified type",
            "AMBIG": "Ambiguous",
        }

        try:
            # 2. Check if error_id column exists
            self.cursor.execute("PRAGMA table_info(entity_occurrences)")
            columns = [column[1] for column in self.cursor.fetchall()]
            if "error_id" not in columns:
                # Add error_id column if it doesn't exist
                self.cursor.execute(
                    """
                    ALTER TABLE entity_occurrences
                    ADD COLUMN error_id VARCHAR(20) DEFAULT NULL
                """
                )
            else:
                self.logger.info("Column error_id already exists in entity_occurrences, clearing")
                self.cursor.execute("UPDATE entity_occurrences SET error_id = NULL")
                self.conn.commit()  

            # 3. Bulk insert error codes
            error_code_data = [(label, desc) for label, desc in error_codes.items()]
            try:
                self.cursor.executemany(
                    "INSERT INTO entity_error_codes (error_id, error_description) VALUES (?, ?)",
                    error_code_data,
                )
                self.logger.info(f"Inserted {len(error_code_data)} new error codes")
            except sqlite3.IntegrityError:
                self.logger.warning("Some error codes already exist.")

            self.conn.commit()

            # 4. Load entity errors from CSV and prepare for bulk update
            entity_updates = []
            entity_id_cache = {}  # Initialize the cache
            with open(error_info, "r") as f:
                reader = csv.reader(f)
                next(reader)  # Skip header row
                for row in reader:
                    entity_type, entity_text, error_id = row

                    # Type checking and validation
                    if not isinstance(entity_text, str):
                        self.logger.warning(f"Invalid entity_text type: {type(entity_text)}. Skipping.")
                        continue
                        
                    if not isinstance(entity_type, str) or len(entity_type) > 20:
                        self.logger.warning(f"Invalid entity_type: {entity_type}. Must be string <= 20 chars. Skipping.")
                        continue
                        
                    if not isinstance(error_id, str) or len(error_id) > 10:
                        self.logger.warning(f"Invalid error_id: {error_id}. Must be string <= 10 chars. Skipping.")
                        continue


                    # Check if entity_id is in the cache
                    if (entity_type, entity_text) in entity_id_cache:
                        entity_id = entity_id_cache[(entity_type, entity_text)]
                    else:
                        # Get the entity_id using get_named_entity_id
                        self.cursor.execute(
                            "SELECT id FROM named_entities WHERE named_entity = ?",
                            (entity_type,),
                        )
                        result = self.cursor.fetchone()
                        if result:
                            entity_id = result[0]
                            entity_id_cache[(entity_type, entity_text)] = (
                                entity_id  # Add to cache
                            )
                        else:
                            self.logger.warning(
                                f"No entity ID found for type: {entity_type} and text: {entity_text}"
                            )
                            continue

                    entity_updates.append(
                        (error_id, entity_text, entity_id)
                    )

            # Print the first 5 updates
            self.logger.info(f"First 5 entity updates: {entity_updates[:5]}")


            # 5. Bulk update entity_occurrences
            update_query = """
            UPDATE entity_occurrences
            SET error_id = ?
            WHERE LOWER(entity_text) = LOWER(?) AND entity_id = ?
            """
            self.cursor.executemany(update_query, entity_updates)
            
            # Get actual matches from entity_occurrences
            matched_query = """
            SELECT DISTINCT entity_text, error_id 
            FROM entity_occurrences 
            WHERE error_id IS NOT NULL
            """
            self.cursor.execute(matched_query)
            updated_entities = set((text, error) for text, error in self.cursor.fetchall())
            
            self.logger.info(f"Updated {len(entity_updates)} entity occurrences")
            self.logger.info(f"Matched entities with errors: {updated_entities}")
            self.conn.commit()

        except FileNotFoundError as e:
            self.logger.error(f"Error: File not found: {e.filename}")
            raise
        except Exception as e:
            self.logger.error(f"Error attaching error information: {e}")
            self.conn.rollback()
            raise
