import re
from typing import List, Tuple, Optional
import sqlite3
from db_data_exchanger import DBDataExchanger
import logging

class DBDataCleaner:
    """Data cleaning utilities for the EasyNer database."""
    def __init__(self, conn: sqlite3.Connection, cursor: sqlite3.Cursor, logger: logging.Logger, data_exchanger: DBDataExchanger):
        self.conn = conn
        self.cursor = cursor
        self.logger = logger
        self.data_exchanger = data_exchanger

    def clean_entity_text_by_pattern(self, patterns: List[str], dry_run: bool = True) -> List[Tuple]:
        """
        Clean entity occurrences by removing leading patterns and adjusting spans.
        
        Args:
            patterns: List of patterns to match at the start of entity_text
            dry_run: If True, only returns affected rows without making changes
            
        Returns:
            List of tuples (id, old_text, new_text, old_span, new_span) for affected rows
        """
        # Convert regex patterns to SQL LIKE patterns
        like_conditions = []
        params = []
        for pattern in patterns:
            # Escape special LIKE characters % and _
            escaped = pattern.replace('%', '\\%').replace('_', '\\_')
            like_conditions.append("entity_text LIKE ? ESCAPE '\\'")
            params.append(f"{escaped}%")
        
        # Find affected entries
        query = f"""
        SELECT id, entity_text, span_start, span_end 
        FROM entity_occurrences 
        WHERE {' OR '.join(like_conditions)}
        """
        
        affected_rows = []
        try:
            self.execute(query, params)
            rows = self.fetchall()
            
            for row in rows:
                id_, text, start, end = row
                # Still use regex for precise matching and capturing
                combined_pattern = f"^({'|'.join(patterns)})"
                match = re.match(combined_pattern, text)
                if match:
                    leading_len = len(match.group(0))
                    new_text = text[leading_len:].strip()
                    new_start = start + leading_len
                    affected_rows.append((id_, text, new_text, (start, end), (new_start, end)))
            
            if not dry_run and affected_rows:
                # Update the database
                update_query = """
                UPDATE entity_occurrences 
                SET entity_text = ?,
                    span_start = ?
                WHERE id = ?
                """
                updates = [(new_text, new_span[0], id_) 
                          for id_, _, new_text, _, new_span in affected_rows]
                
                self.bulk_insert(update_query, updates)
                self.commit()
                self.logger.info(f"Updated {len(updates)} entity occurrences")
                
        except Exception as e:
            self.logger.error(f"Error cleaning entity text: {e}")
            if not dry_run:
                self.rollback()
            raise
            
        return affected_rows


    def clean_inclusive_entity_spans(self, entity_type: str = None) -> None:
        """ 
        This fixes an error that seems to be produced when running the phrasematcher which produces inclusive span_end values in the entity_occurrences table, which is not the expected behavior.

        Python convention is to use exclusive end indices, which is what seem to be used for the entities generated by the NER model. 
        
        This function will adjust the span_end values to be exclusive for all entity occurrences in the database of a given entity type.

        Args:
            entity_type: The type of entity to clean
            entity_id: The ID of

        """
        
        if entity_type is None:
            raise ValueError("entity_type must be specified")
        
        try:
            entities = self.data_exchanger.search_entities(type=entity_type)
            
            update_data = []
            for entity in entities:
                update_data.append((entity['span_end'] + 1, entity['id']))

            if update_data:
                update_query = """
                UPDATE entity_occurrences
                SET span_end = ?
                WHERE id = ?
                """
                self.data_exchanger.bulk_insert(update_query, update_data)
                self.conn.commit()
                self.logger.info(f"Updated span_end for {len(update_data)} entity occurrences of type {entity_type}")
            else:
                self.logger.info(f"No entity occurrences of type {entity_type} needed span adjustment.")

        except Exception as e:
            self.logger.error(f"Error cleaning inclusive entity spans: {e}")
            self.conn.rollback()
            raise